#
# Mod Info
#
mod_version = 1.16.2+26.1.2-prerelease
minecraft_version=26.1.2
archives_base_name = splitscreen

#
# Mod Dependencies
# https://fabricmc.net/develop
#
fabric_loader_version=0.18.4
fabric_api_version=0.146.1+26.1.2

#
# Plugin Dependencies
#
fabric_loom_version = 1.15-SNAPSHOT
curseforgegradle_plugin_version = 1.1.25
minotaur_plugin_version = 2.+

#
# Publishing Info
#
github_projectUrl = https://github.com/pcal43/splitscreen-support
modrinth_projectId = yJgqfSDR
curseforge_projectId = 909164

#
# Build Settings
#
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.jvmargs = -Xmx4G
java_version = 25
